# Generated by Django 3.1.7 on 2021-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_cook_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_prep_time',
            field=models.DurationField(),
        ),
    ]
