# Generated by Django 3.1.6 on 2021-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210401_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
